# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://beta.ruff.rs
name: codespell_and_ruff
on:
  push:
  #  branches: [main]
  pull_request:
    branches: [main]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell --ignore-words-list="alph,ans,nd"  # --skip="*.css,*.js,*.lock,*.po"
    - run: ruff --exit-zero --select=ALL --statistics --target-version=py38 . | sort -k2
    - run: ruff --format=github --select=E9,F63,F7 --target-version=py38
                --exclude=adder_reddit.py,adventure-text.py,horoscope.py,reddit_dict_iter_tester.py,reddit_pconfig.py,reddit_spn.py,reddit_tax.py,reddit_test_multiline_add.py,simple_reddit.py .
    - run: ruff --format=github --select=E9,F63,F7,F82 --target-version=py38 \
                --exclude=adder_reddit.py,adventure-text.py,horoscope.py,reddit_dict_iter_tester.py,reddit_pconfig.py,reddit_spn.py,reddit_tax.py,reddit_test_multiline_add.py,simple_reddit.py .
    - run: ruff --format=github --line-length=200 --target-version=py38
                --exclude=adder_reddit.py,adventure-text.py,horoscope.py,reddit_dict_iter_tester.py,reddit_pconfig.py,reddit_spn.py,reddit_tax.py,reddit_test_multiline_add.py,simple_reddit.py .
    - run: ruff --format=github --target-version=py38
                --exclude=adder_reddit.py,adventure-text.py,horoscope.py,reddit_dict_iter_tester.py,reddit_pconfig.py,reddit_spn.py,reddit_tax.py,reddit_test_multiline_add.py,simple_reddit.py .

